# Generated by Django 3.1.3 on 2020-11-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201121_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_ft',
            field=models.IntegerField(),
        ),
    ]
