# Generated by Django 3.1.3 on 2020-11-23 05:24

import django.core.validators
from django.db import migrations, models
import realtors.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20201121_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, default='photos/%Y/%m/%d/', null=True, upload_to=realtors.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
